-- CREATE EXTENSION
CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE USER IF NOT EXIST
DO
$$
BEGIN
  IF
NOT EXISTS (SELECT 1 FROM pg_user WHERE usename = 'ch') THEN
CREATE ROLE ch WITH ENCRYPTED PASSWORD 'ch';
END IF;
END $$;
-- CREATE DATABASE IF NOT EXIST
DO
$$
BEGIN
  IF
NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'ch') THEN
CREATE
DATABASE ch WITH OWNER ch;
END IF;
END $$;
